### ISSUE TITLE
about  infer   speed? 

### ISSUE THREAD

**Issue by zhanghongyong123456** [WindVChen/INR-Harmonization#1]
I didn't find anything about the speed of reasoning.What is the speed of inference

**Comment by WindVChen** [comment]
Hi @zhanghongyong123456 ,

The following table takes a single 2048x2048 image as an example and compares the efficiency of our method with existing methods from the perspective of model parameters (Params), calculation amount (MACs), memory overhead (Mem) during training and inference, and inference runtime (Time). For the memory cost and runtime of inference, we show results when the input is split into 1/4/16 parts (splitting script will be released recently. Check it in [TODO](https://github.com/WindVChen/INR-Harmonization#todo)). 

Due to the Random Step Crop (RSC) strategy designed in Section 3.4, our training memory cost is less than 3GB among all methods. By varying the number of input splits (splitting will not affect the performance due to the characteristic of INR), we can achieve competitive performance with color-to-color (C2C) methods either on inference memory cost or runtime.

<div align=center><img src="https://github.com/WindVChen/INR-Harmonization/assets/56162412/113318d3-4899-43c8-a13d-bc0e7f42b891"></div>

(Note: OOM denotes out-of-memory)

We will also update these in new editions of the paper.

**Comment by WindVChen** [comment]
Hi @zhanghongyong123456 ,

I would like to inform you that we have updated the efficient inference script in our latest version. Hope you enjoy that. 😃

**Comment by zhanghongyong123456** [comment]
> Hi @zhanghongyong123456 ,
> 
> I would like to inform you that we have updated the efficient inference script in our latest version. Hope you enjoy that. smiley

ok,thank you very much
